let enums = {
    School: [
        'Inherit',
        'Abjuration',
        'Conjuration',
        'Divination',
        'Enchantment',
        'Evocation',
        'Illusion',
        'Necromancy',
        'Transmutation',
        'Other'
    ],
    TimeSuffix: [
        'Inherit',
        'None_Instantaneous',
        'ShortRest',
        'LongRest',
        'FreeAction',
        'Reaction',
        'BonusAction',
        'Action',
        'Second',
        'Minute',
        'Hour',
        'Day',
        'Week',
        'Month',
        'Year',
        'Decade',
        'Century',
        'Millenia'
    ],
    Range:[
        'Inherit',
        'Self',
        'Touch',
        'Distance'
    ],
};